# -*- coding: utf-8 -*-

"""
Analysis and preprocessing package for LAMMPS simulations

Sub packages:
  * trajectory: Analysis/Processing of simulation trajectory data from LAMMPS
  * cluster: Analysis/Processing of cluster analysis files generated by Ovito
"""

from . import trajectory
from . import cluster
