import numpy as np
import pandas as pd
import xarray as xr
import itertools
import io
import os
import gzip
from itertools import islice
import re


def read_header(filename):
    """
    Reads the header of a cluster analysis results file

    :param filename: name of file
    :type filename: string
    :return: Atom properties, header string and atom count
    :rtype: list, string and int
    """
    header = {"id":("ID",),
            "species":("Type",),
            "pos":("X","Y","Z"),
            "velo":("VX","VY","VZ"),
            "velo_mag":("Velocity",),
            "mass":("Mass",),
            "cluster":("Cluster",)
    }

    line_header = ''
    atom_count = 0

    with open(filename) as file:
        for line in islice(file, 0, 1):
            atom_count = int(line)

    pattern = re.compile(r'([a-z,_]+)')
    with open(filename) as file:
        for line in islice(file, 1, 2):
            line_header = line
            split_line = line.split("Properties=")[1]
            properties = pattern.findall(split_line)

    filtered_properties = []

    for key in header:
        for property in properties:
            if key == property:
                for value in header[key]:
                    filtered_properties.append(value)
    
    return filtered_properties, line_header, atom_count


def read_cluster_data(filename, frames_to_read):
    """
    Reads in data generated by Ovito's cluster analysis function and exported as xyz file

    :param filename: name of file
    :type filename: string
    :param frames_to_read: number of cluster data frames ("timesteps") to read
    :type frames_to_read: int
    :return: cluster analysis result and atom properties for each read frame
    :rtype: xarray
    """
    n_frames = 0
    n_lines = 0
    time = 0
    data = []

    # todo: use gzip object if gzip, use file else...
    basename, ext = os.path.splitext(filename)
    if ext == ".gz":
        open_fct = gzip.open
    else:
        open_fct = open

    properties, header_string, atom_count = read_header(filename)
    with open_fct(filename, mode='rt') as fh:
        for line in fh:
            if str(atom_count) in line:
                #a new timestep has begun
                n_frames += 1
                time += 1
                n_lines += 1
            else:
                n_lines += 1
                parcoords = properties

                strio = io.StringIO()
                lines = itertools.islice(fh, atom_count)
                for line_str in lines:
                    strio.write(line_str)
                strio.seek(0)
                
                dat = pd.read_csv(strio, sep=' ', header=None).values[:, :]
                dat = pd.DataFrame(dat, columns=properties)
            

                data.append(
                    xr.DataArray(dat, dims=('particles', 'params'), coords={'params': parcoords, 'time': time}, name="Trajectories")
                )
                n_lines += atom_count
                
            if frames_to_read and n_frames >= frames_to_read:
                break

    combined_data = xr.concat(data, dim='time') 
    return combined_data

def filter_frame(trajectory, timestep):
	"""
	Filters out a single timeframe as dataframe
	(The returned frames is not sorted according to id's)

	:param trajectory: Cluster trajectory
	:type trajectory: xarray
	:param timestep: The timestep of the selected frame
	:type timestep: int
	:return: filtered frame 
	:rtype: dataframe (pandas)
	"""
	selected_ts = trajectory[timestep]
	return selected_ts.to_pandas()

def xarray_filter_frame(trajectory, timestep):
	"""
	Filters out a single timeframe as xarray
	(The returned frames is not sorted according to id's)

	:param trajectory: Cluster trajectory
	:type trajectory: xarray
	:param timestep: The timestep of the selected frame
	:type timestep: int
	:return: filtered frame 
	:rtype: xarray
	"""
	selected_ts = trajectory[timestep]
	return selected_ts

def xarray_filter_species_frame(trajectory, timestep, species):
	"""
	Filters out a single timeframe as xarray with selected species
	(The returned frames is not sorted according to id's)

	:param trajectory: Cluster trajectory
	:type trajectory: xarray
	:param timestep: The timestep of the selected frame
	:type timestep: int
	:param species: A list of species type id's which are selected
	:type species: list of int
	:return: filtered frame
	:rtype: xarray
	"""
	selected_ts = trajectory[timestep]
	frame = selected_ts[(np.in1d(selected_ts.loc[:, 'Type'], species))]
	return frame

def filter_trajectory(trajectory, species):
	"""
	Filters out cluster data trajectory of selected species from Ovito cluster data.

	:param trajectory: Cluster trajectory
	:type trajectory: xarray
	:param species: A list of species type id's which are selected
	:type species: list of int
	:return: filtered cluster trajectory
	:rtype: xarray
	"""
	n_frames = trajectory.sizes['time']
	buf = []
	for i in range(n_frames):
		frame_unsorted = xarray_filter_species_frame(trajectory, i, species)
		buf.append(frame_unsorted)
	result = xr.concat(buf, dim='time')
	return result